[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$zvkfQ.gdgxAihLCWMoZwDg$T37g4s2/RyVw.ij1JSLBYpzdYNq8xzupLDDEJLs05kTt7k49aB76Irc/.zU1pQXI7PotTtFWEk2kNMK1e4KXfg
list_db = True

